interface OverallReviewsData{
    sprint:number;
    acceleration:number;
    finishing:number;
    longShots:number;
    shotPower:number;
    curl:number;
    weakFootUsage:number;
    shortPassing:number;
    longPassing:number;
    vision:number;
    crossing:number;
    weakFootAccuracy:number;
    ballControl:number;
    composure:number;
    balance:number;
    agility:number;
    strength:number;
    stamina:number;
    jumping:number;
    reactions:number;
    headingAccuracy:number;
    marking:number;
    interceptions:number;
    standingTackle:number;
    slidingTackle:number;
    gKReflexes:number;
    gKCatching:number;
    gKClearing:number;
    gKReach:number;
    gKPositioning:number;
    SPD:number;
    SHO:number;
    PAS:number;
    DRI:number;
    DEF:number;
    PHY:number;
    GKP:number;
    reviewComment:string
    id:string;
    country:object[];
    isPlayerGoalkeeper:boolean;
    TDF:number;
    usersThatSentReviews:object[]
    usersThatWereReviewed:object[]
}

export default OverallReviewsData